Fix missing struct members `s6_addr32' and `s6_addr16' on OSX.
Like FreeBSD, `in6_addr` doesn't have a struct member called `s6_addr32' or
`s6_add16' on Mac OS X.

This commit adds OSX to the controlled group that replaces:

    `s6_addr32' with `__u6_addr.__u6_addr32'
    `s6_addr16' with `__u6_addr.__u6_addr16'

Sample of errors thrown:

```
src/libproxychains.c:332:12: error: no member named 's6_addr32' in 'struct in6_addr'
        return a->s6_addr32[0] == 0 && a->s6_addr32[1] == 0 &&
               ~  ^

src/libproxychains.c:337:36: error: no member named 's6_addr16' in 'struct in6_addr'
               a->s6_addr16[4] == 0 && a->s6_addr16[5] == 0xffff;
                                       ~  ^
```

For further explanation also see this PassiveDNS project commit:

https://github.com/gamelinux/passivedns/commit/42dbd6c5ae8bf4b6bcac38e0a5de41448b8ad777